version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: zentropy_db
    environment:
      POSTGRES_USER: zentropy
      POSTGRES_PASSWORD: zentropy
      POSTGRES_DB: zentropy
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
